/**
 * File              : interface.c
 * Author            : Igor V. Sementsov <ig.kuzm@gmail.com>
 * Date              : 12.04.2023
 * Last Modified Date: 12.04.2023
 * Last Modified By  : Igor V. Sementsov <ig.kuzm@gmail.com>
 */
/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mainWindow (void)
{
  GtkWidget *mainWindow;
  AtkObject *atko;
  GtkWidget *vbox1;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *remove;
  GtkWidget *separatortoolitem1;
  GtkWidget *excel;
  GtkWidget *hpaned1;
  GtkWidget *zakaziScrolledWindow;
  GtkWidget *zakaziTreeView;
  GtkWidget *dataScrolledWindow;
  GtkWidget *dataTreeView;
  GtkWidget *info;

  mainWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (mainWindow, 1000, 600);
  gtk_window_set_title (GTK_WINDOW (mainWindow), _("\320\227\320\260\320\272\320\260\320\267 \320\272\320\276\320\275\320\274\320\265\321\202"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (mainWindow), vbox1);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_TEXT);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  remove = (GtkWidget*) gtk_tool_button_new (NULL, _("-"));
  gtk_widget_show (remove);
  gtk_container_add (GTK_CONTAINER (toolbar1), remove);

  separatortoolitem1 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (separatortoolitem1);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem1);

  excel = (GtkWidget*) gtk_tool_button_new (NULL, _("excel"));
  gtk_widget_show (excel);
  gtk_container_add (GTK_CONTAINER (toolbar1), excel);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (vbox1), hpaned1, TRUE, TRUE, 0);

  zakaziScrolledWindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (zakaziScrolledWindow);
  gtk_paned_pack1 (GTK_PANED (hpaned1), zakaziScrolledWindow, FALSE, TRUE);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (zakaziScrolledWindow), GTK_SHADOW_IN);

  zakaziTreeView = gtk_tree_view_new ();
  gtk_widget_show (zakaziTreeView);
  gtk_container_add (GTK_CONTAINER (zakaziScrolledWindow), zakaziTreeView);

  dataScrolledWindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (dataScrolledWindow);
  gtk_paned_pack2 (GTK_PANED (hpaned1), dataScrolledWindow, TRUE, TRUE);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (dataScrolledWindow), GTK_SHADOW_IN);

  dataTreeView = gtk_tree_view_new ();
  gtk_widget_show (dataTreeView);
  gtk_container_add (GTK_CONTAINER (dataScrolledWindow), dataTreeView);

  info = gtk_label_new ("");
  gtk_widget_show (info);
  gtk_box_pack_start (GTK_BOX (vbox1), info, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) mainWindow, "destroy",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) remove, "clicked",
                    G_CALLBACK (on_remove_clicked),
                    NULL);
  g_signal_connect ((gpointer) excel, "clicked",
                    G_CALLBACK (on_excel_clicked),
                    NULL);

  atko = gtk_widget_get_accessible (mainWindow);
  atk_object_set_name (atko, _("\320\227\320\260\320\272\320\260\320\267 \320\272\320\276\320\275\320\274\320\265\321\202"));


  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mainWindow, mainWindow, "mainWindow");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (mainWindow, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (mainWindow, remove, "remove");
  GLADE_HOOKUP_OBJECT (mainWindow, separatortoolitem1, "separatortoolitem1");
  GLADE_HOOKUP_OBJECT (mainWindow, excel, "excel");
  GLADE_HOOKUP_OBJECT (mainWindow, hpaned1, "hpaned1");
  GLADE_HOOKUP_OBJECT (mainWindow, zakaziScrolledWindow, "zakaziScrolledWindow");
  GLADE_HOOKUP_OBJECT (mainWindow, zakaziTreeView, "zakaziTreeView");
  GLADE_HOOKUP_OBJECT (mainWindow, dataScrolledWindow, "dataScrolledWindow");
  GLADE_HOOKUP_OBJECT (mainWindow, dataTreeView, "dataTreeView");
  GLADE_HOOKUP_OBJECT (mainWindow, info, "info");

  return mainWindow;
}

