/**
 * File              : main.c
 * Author            : Igor V. Sementsov <ig.kuzm@gmail.com>
 * Date              : 05.04.2023
 * Last Modified Date: 13.04.2023
 * Last Modified By  : Igor V. Sementsov <ig.kuzm@gmail.com>
 */
/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include <locale.h> 

#include "interface.h"
#include "support.h"

#include "zakaz.h"
#include "zakazi_view.h"
#include "data_view.h"

int
main (int argc, char *argv[])
{
  GtkWidget *mainWindow;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

#ifdef _WIN32
  #include <windows.h> 
  #include <winbase.h> 
#else
  setenv("LANG", "C", 1);
#endif  

  gtk_init (&argc, &argv);
  
  setlocale( LC_NUMERIC, "C" );
  
  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  mainWindow = create_mainWindow ();
  gtk_widget_show (mainWindow);

  //init zakaz database
  zakaz_init(argv);

  //load zakazi view
  zakazi_new(mainWindow);

  //load data view
  data_view_new(mainWindow);  

  gtk_main ();
  return 0;
}

